name: Deploy Github Pages
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.35.0"

      - name: Generate
        run: deno run -A mod.ts

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pages
